### ISSUE TITLE
feat: analysis tools endpoint

### ISSUE THREAD

**Issue by Enderchief** [Endercheif/piston#4]
## Feature Description
Ability to run tools such as `ruff` (python), `clippy` (rust), `eslint` (javascript), etc. on code of a given languages.

## Tasks to Implement

- [x] Endpoint to get list of tools
- [x] Endpoint to run a tool
- [x] Add the tools
- [x] Stuff that runs the tools

**Comment by Enderchief** [comment]
## Sample usage

`POST /api/v3/analysis`
```json
{
  "language": "python",
  "tool": "ruff",
  "files": [{"content": "import time\n\nprint(\"time is not used\")\n"}]
}
```

response:
```json
{
  "language": "python",
  "tool": "ruff",
  "run": {
    "stdout": "",
    "stderr": "foo:1:8: F401 [*] `time` imported but unused\nFound 1 error.\n[*] 1 potentially fixable with the --fix option.",
    "output": "foo:1:8: F401 [*] `time` imported but unused\nFound 1 error.\n[*] 1 potentially fixable with the --fix option.",
    "code": 1
  }
}
```
